name: Release

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed
    branches: [master]

jobs:
  release:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.3.0

    - name: Build gem
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        gem build *.gemspec

    - uses: rubygems/release-gem@v1
